import Navbar from '@/components/Navbar'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="max-w-2xl mx-auto px-4 py-8">
        <h1 className="text-3xl font-heading font-bold text-text-primary mb-2">Privacy Policy</h1>
        <p className="text-text-muted text-sm mb-8">Last updated: March 2026</p>

        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          Cosmos (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is operated by Zama Khumalo, based in the Republic of South Africa. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use the Cosmos AI Voice Note Taker application (&quot;Service&quot;).
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">1. Information We Collect</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          We collect the following categories of information:
        </p>
        <ul className="list-disc list-inside text-text-secondary text-sm space-y-1 mb-4">
          <li><strong className="text-text-primary">Account information:</strong> your name, email address, and a securely hashed password when you register.</li>
          <li><strong className="text-text-primary">Voice note transcripts:</strong> the text transcriptions of your voice recordings. We do not store audio recordings (see Section 7 below).</li>
          <li><strong className="text-text-primary">AI-generated content:</strong> titles, summaries, action items, key decisions, tags, and emoji generated by our AI processing.</li>
          <li><strong className="text-text-primary">Payment information:</strong> subscription and payment data processed by PayFast. We do not store your credit card details directly.</li>
          <li><strong className="text-text-primary">Usage data:</strong> note counts, subscription status, and feature usage necessary to enforce plan limits.</li>
        </ul>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">2. How We Use Your Information</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          We use your information to:
        </p>
        <ul className="list-disc list-inside text-text-secondary text-sm space-y-1 mb-4">
          <li>Provide, maintain, and improve the Cosmos service.</li>
          <li>Process your voice note transcripts through AI (Anthropic Claude API) to generate polished text, summaries, and insights.</li>
          <li>Manage your account, authentication, and subscription billing.</li>
          <li>Communicate with you about your account, service updates, or policy changes.</li>
          <li>Enforce our Terms of Use and protect against misuse.</li>
        </ul>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">3. Data Storage and Security</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          Your data is stored in a Neon Postgres database hosted in the US East region. All data is encrypted at rest and transmitted over SSL/TLS. Passwords are hashed using bcryptjs and are never stored in plain text. We use JWT-based sessions stored in HTTP-only cookies.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">4. Third-Party Services</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          We use the following third-party services to operate Cosmos:
        </p>
        <ul className="list-disc list-inside text-text-secondary text-sm space-y-1 mb-4">
          <li><strong className="text-text-primary">Anthropic (Claude API):</strong> processes your note transcripts to generate AI-powered insights, summaries, and polished text. Transcript text is sent to Anthropic&apos;s API for processing.</li>
          <li><strong className="text-text-primary">PayFast:</strong> handles subscription payments and billing. Your payment details are processed directly by PayFast and are subject to their privacy policy.</li>
          <li><strong className="text-text-primary">Netlify:</strong> hosts the Cosmos web application.</li>
          <li><strong className="text-text-primary">Neon:</strong> provides the managed Postgres database where your account and note data is stored.</li>
        </ul>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">5. Data Retention</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          Your account data and notes are retained for as long as your account is active. Individual notes are deleted immediately when you choose to delete them. If you wish to delete your entire account and all associated data, you may request this by contacting us (see Section 10).
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">6. Your Rights</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          You have the right to:
        </p>
        <ul className="list-disc list-inside text-text-secondary text-sm space-y-1 mb-4">
          <li>Access the personal information we hold about you.</li>
          <li>Request a copy or export of your data.</li>
          <li>Correct inaccurate information on your account.</li>
          <li>Delete your notes or request full account deletion.</li>
          <li>Object to or restrict certain processing of your data.</li>
        </ul>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          To exercise any of these rights, please contact us at zamolucas@gmail.com.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">7. No Audio Storage</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          Cosmos uses the Web Speech API built into your browser to convert speech to text. All audio processing happens locally in your browser. No audio recordings are ever sent to or stored on our servers. Only the resulting text transcript is transmitted and stored.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">8. Cookies</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          We use essential session cookies to keep you signed in. These are HTTP-only, secure cookies containing your authentication token. We do not use tracking cookies, advertising cookies, or any third-party analytics cookies.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">9. POPIA Compliance</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          As a South African service, we comply with the Protection of Personal Information Act (POPIA). We process your personal information lawfully and only for the purposes described in this policy. You may lodge a complaint with the Information Regulator of South Africa if you believe your privacy rights have been infringed.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">10. Children</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          Cosmos is not intended for use by anyone under the age of 18. We do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact us so we can take appropriate action.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">11. Changes to This Policy</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          We may update this Privacy Policy from time to time. If we make material changes, we will notify you by email at the address associated with your account. Your continued use of the Service after such notification constitutes acceptance of the updated policy.
        </p>

        <h2 className="text-xl font-heading font-semibold text-text-primary mt-8 mb-3">12. Contact Us</h2>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          If you have any questions about this Privacy Policy or your personal data, please contact:
        </p>
        <p className="text-text-secondary text-sm leading-relaxed mb-4">
          Zama Khumalo<br />
          Email: zamolucas@gmail.com
        </p>
      </main>
    </div>
  )
}
